import { Expect } from "./Expect.js"
const failures = new Expect('Expect Failures Tests')
.equal('not an array', [1,2,3], 4)
.equal('array not equal', [1,2,3], [3,2,1])
.alike('array are alike', [1,2,3], [3,2,1])
.alike('array not same length', [1,2,3], [3,2,1,0])
.equal('not an object', {a: 1, b:2}, {})
.equal('object missing key', {a: 1, b:2}, {a: 2})
.equal('object key unequal', {a: 1, b:2}, {a: 2, b:2})
.summary()
