export class Paths {
    // Configs
    static cfgCanopy      = 'canopy/height/inputs'
    static cfgEffWind     = 'surface/fire/effective wind speed limit'
    static cfgEllipse     = 'ellipse/fire/inputs'
    static cfgVectors     = 'ellipse/fire/vectors'
    static cfgCured       = 'surface/fuel/curing fraction/parameter'
    static cfgMidflame    = 'surface/midflame/wind speed/parameter'
    static cfgWsrf        = 'surface/midflame/wind speed reduction/parameter'
    static cfgMoisDead    = 'surface/moisture/dead/inputs'
    static cfgMoisLive    = 'surface/moisture/live/inputs'
    static cfgFuelDomain1 = 'surface/primary/fuel/domain'
    static cfgFuelDomain2 = 'surface/secondary/fuel/domain'
    static cfgStdInput1   = 'surface/primary/standard model/input'
    static cfgStdInput2   = 'surface/secondary/standard model/input'
    static cfgSurfWtg     = 'surface/weighting/method'   // = ['primary', 'harmonic', 'arithmetic']'
    static cfgSlopeDir    = 'terrain/slope/direction/input'
    static cfgSlopeSteep  = 'terrain/slope/steepness/input'
    static cfgWindDir     = 'weather/wind/direction/input'
    static cfgWindSpeed   = 'weather/wind/speed/input'
    // Not yet implemented
    static cfgChapInput1  = 'primary/chaparral/total load/parameter'   // ['input', 'estimated'][0]],
    static cfgChapInput2  = 'secondary/chaparral/total load/parameter'   // ['input', 'estimated'][0]],

    // Fire Ellipse model
    static cfgLwr = 'ellipse/length-to-width ratio/parameter' // ['input', 'estimated'][0]],
    static cfgFli = 'ellipse/fireline intensity/parameter'    // ['fireline intensity', 'flame length'][1]],
    // Fire Growth links with Surface Fire: 'input' is unlinked,
    // 'surface' uses surface fire direction, spread rate, fli, lwr, and eff wind
    static cfgEffLink = 'ellipse/parameters'  // ['input', 'surface'][0]],

    // CanopyModule
    static canopySelf     = 'canopy/'
    static canopyMod      = 'CanopyModule'
    static canopyCover    = 'coverage'
    static canopyBase     = 'crown/base height'
    static canopyLength   = 'crown/length'
    static canopyRatio    = 'crown/ratio'
    static canopyHeight   = 'crown/total height'
    static canopyBulk     = 'fuel/bulk density'
    static canopyLoad     = 'fuel/ovendry load'
    static canopyVol      = 'fuel/volumetric fill ratio'
    static canopyHeat     = 'fire/heat of combustion'
    static canopyHpua     = 'fire/heat per unit area'
    static canopyShelters = 'shelters fuel from wind'
    static canopyWsrf     = 'wind/speed/reduction/factor'

    // ConstantsModule
    static constantsSelf = 'constants/'
    static constantsMod  = 'ConstantsModule'
    static fuelDeadCat   = 'constants/fuel/life/dead category'
    static fuelLiveCat   = 'constants/fuel/life/live category'
    static fuelUnused    = 'constants/fuel/type/unused'
    static zero          = 'constants/zero'
    static one           = 'constants/one'

    // DeadFuelMoistureModule
    static moisDeadMod  = 'DeadFuelMoistureModule'
    static moisDeadSelf = 'moisture/dead/'
    static moisDeadCat  = 'category'
    static moisDead1    = '1-h'
    static moisDead10   = '10-h'
    static moisDead100  = '100-h'

    // FireEllipseModule
    static ellipseMod  = 'FireEllipseModule'
    static ellipseSelf = 'ellipse/'
    static ellEccent   = 'eccentricity'

    static axisLw     = 'axis/length-to-width ratio'
    static axisFRos   = 'axis/f/spread rate'
    static axisGRos   = 'axis/g/spread rate'
    static axisHRos   = 'axis/h/spread rate'
    static axisMajRos = 'axis/major/spread rate'
    static axisMinRos = 'axis/minor/spread rate'

    static headDist  = 'heading/distance'
    static headMap   = 'heading/map distance'
    static headRos   = 'heading/spread rate'
    static headFlame = 'heading/flame length'
    static headFli   = 'heading/fireline intensity'
    static headScorch= 'heading/scorch height'
    static headMort  = 'heading/tree mortality'

    static backDist    = 'backing/distance'
    static backMap     = 'backing/map distance'
    static backRos     = 'backing/spread rate'
    static backFlame   = 'backing/flame length'
    static backFli     = 'backing/fireline intensity'
    static backScorch  = 'backing/scorch height'
    static backMort    = 'backing/tree mortality'

    static flankDist   = 'flanking/distance'
    static flankMap    = 'flanking/map distance'
    static flankRos    = 'flanking/spread rate'
    static flankFlame  = 'flanking/flame length'
    static flankFli    = 'flanking/fireline intensity'
    static flankScorch = 'flanking/scorch height'
    static flankMort   = 'flanking/tree mortality'

    static betaDist   = 'beta/distance'
    static betaMap    = 'beta/map distance'
    static betaRos    = 'beta/spread rate'
    static betaFlame  = 'beta/flame length'
    static betaFli    = 'beta/fireline intensity'
    static betaScorch = 'beta/scorch height'
    static betaMort   = 'beta/tree mortality'
    static betaPsi    = 'beta/psi/degrees'
    static betaPsiRos = 'beta/psi/spread rate'
    static betaTheta  = 'beta/theta/degrees'

    static beta5Dist  = 'beta5/distance'
    static beta5Map   = 'beta5/map distance'
    static beta5Ros   = 'beta5/spread rate'
    static beta5Flame = 'beta5/flame length'
    static beta5Fli   = 'beta5/fireline intensity'
    static beta5Scorch= 'beta5/scorch height'
    static beta5Mort  = 'beta5/tree mortality'

    static psiDist    = 'psi/distance'
    static psiMap     = 'psi/map distance'
    static psiRos     = 'psi/spread rate'
    static psiFlame   = 'psi/flame length'
    static psiFli     = 'psi/fireline intensity'
    static psiSh      = 'psi/scorch height'
    static psiMort    = 'psi/tree mortality'

    static sizeArea   = 'size/area'
    static sizeLength = 'size/length'
    static sizePerim  = 'size/perimeter'
    static sizeWidth  = 'size/width'

    static mapArea   = 'map/area'
    static mapLength = 'map/length'
    static mapPerim  = 'map/perimeter'
    static mapWidth  = 'map/width'

    // LiveFuelCuringModule
    static curingMod       = 'LiveFuelCuringModule'
    static curingSelf      = 'curing/'
    static curingFraction  = 'fraction/'
    static curingApplied   = 'fraction/applied'
    static curingEstimated = 'fraction/estimated'
    static curingObserved  = 'fraction/observed'

    // LiveFuelMoistureModule
    static moisLiveMod  = 'LiveFuelMoistureModule'
    static moisLiveSelf = 'moisture/live/'
    static moisLiveCat  = 'category'
    static moisLiveHerb = 'herb'
    static moisLiveStem = 'stem'

    // MidflameWindSpeedModule
    static midflameMod   = 'MidflameWindSpeedModule'
    static midflameSelf  = 'wind/speed/'
    static midflame      = 'midflame'

    // SlopeDirectionModule
    static slopeDirMod  = 'SlopeDirectionModule'
    static slopeDirSelf = 'slope/direction/'
    static slopeUp      = 'up-slope'
    static slopeDown    = 'down-slope'

    // SlopeSteepnessModule
    static slopeSteepMod  = 'SlopeSteepnessModule'
    static slopeSteepSelf = 'slope/steepness/'
    static slopeDegrees   = 'degrees'
    static slopeRatio     = 'ratio'

    // StandardFuelModelModule
    static stdMod           = 'StandardFuelModelModule'
    static stdSelf          = 'standard/'
    static stdCode          = 'info/code'
    static stdNumb          = 'info/number'
    static stdLabel         = 'info/label'
    static stdAuth          = 'info/author'

    static stdDens          = 'fiber density'
    static stdDepth         = 'depth'
    static stdKey           = 'key'
    static stdSeff          = 'mineral content/silica-free'
    static stdStot          = 'mineral content/total'
    static stdDeadHeat      = 'dead/heat of combustion'
    static stdDeadMext      = 'dead/extinction moisture content'
    static stdLiveHeat      = 'live/heat of combustion'
    
    static stdDead1Load     = 'dead/1-h/ovendry fuel load'
    static stdDead1Mois     = 'dead/1-h/moisture content'
    static stdDead1Savr     = 'dead/1-h/surface area-to-volume ratio'
    static stdDead1Type     = 'dead/1-h/fuel type'

    static stdDead10Load    = 'dead/10-h/ovendry fuel load'
    static stdDead10Mois    = 'dead/10-h/moisture content'
    static stdDead10Savr    = 'dead/10-h/surface area-to-volume ratio'
    static stdDead10Type    = 'dead/10-h/fuel type'
    
    static stdDead100Load   = 'dead/100-h/ovendry fuel load'
    static stdDead100Mois   = 'dead/100-h/moisture content'
    static stdDead100Savr   = 'dead/100-h/surface area-to-volume ratio'
    static stdDead100Type   = 'dead/100-h/fuel type'

    static stdDeadHerbLoad  = 'dead/herb/ovendry fuel load'
    static stdDeadHerbMois  = 'dead/herb/moisture content'
    static stdDeadHerbSavr  = 'dead/herb/surface area-to-volume ratio'
    static stdDeadHerbType  = 'dead/herb/fuel type'

    static stdLiveHerbLoad  = 'live/herb/ovendry fuel load'
    static stdLiveHerbMois  = 'live/herb/moisture content'
    static stdLiveHerbSavr  = 'live/herb/surface area-to-volume ratio'
    static stdLiveHerbType  = 'live/herb/fuel type'

    static stdLiveStemLoad  = 'live/stem/ovendry fuel load'
    static stdLiveStemMois  = 'live/stem/moisture content'
    static stdLiveStemSavr  = 'live/stem/surface area-to-volume ratio'
    static stdLiveStemType  = 'live/stem/fuel type'

    static stdTotalHerbLoad = 'total/herb/ovendry fuel load'
    static stdTotalHerbSavr = 'total/herb/surface area-to-volume ratio'
    static stdTotalHerbType = 'total/herb/fuel type'

    // SurfaceFireModule
    static fireMod   = 'SurfaceFireModule'
    static fireSelf  = 'fire/'
    static firep1    = '1 no-wind no-slope/'       // 'spread rate',
    static firep2    = '2 wind-slope additional/'  // 'spread rate', 'spread rate/slope only', '.../wind only', '.../x component', '.../y component'
    static firep3    = '3 cross-slope wind/'       // 'spread rate', 'effective wind/speed', 'effective wind/coefficient'
    static firep4    = '4 effective limit/'        // 'spread rate', 'effective wind/speed', 'effective wind/coefficient'
    static firep5    = '5 eff wind limit applied/' // 'spread rate', 'effective wind/speed', 'effective wind/coefficient'
    static firep6    = '6 ros limit applied/'      // 'spread rate', 'effective wind/speed', 'effective wind/coefficient'
    static firep7    = '7 both limits applied/'
    static fireHeadFlame = 'heading/flame length'
    static fireHeadFli   = 'heading/fireline intensity'
    static fireHeadRos   = 'heading/spread rate'
    static fireHeadDirUp = 'heading/direction/from up-slope'
    static fireHeadDirNo = 'heading/direction/from north'
    static fireHpua      = 'heat per unit area'
    static fireLwr       = 'length-to-width ratio'
    static fireMidf      = 'wind/speed/midflame'
    static firePhiE      = 'spread rate coefficient/effective wind'
    static firePhiS      = 'spread rate coefficient/slope'
    static firePhiW      = 'spread rate coefficient/wind'
    static fireRos       = 'spread rate'
    static fireRosXcomp  = 'spread rate/x component'
    static fireRosYcomp  = 'spread rate/y component'
    static fireRosSlope  = 'spread rate/slope only'
    static fireRosWind   = 'spread rate/wind only'
    static fireTaur      = 'residence time'
    static fireWeff      = 'effective wind/speed'
    static fireWeffLim   = 'effective wind/speed/limit'
    static fireWeffX     = 'effective wind/speed/exceeded'

    static fireRxi   = 'reaction intensity'      // MUST BE SAME AS fuelRxi
    static fireSlpk  = 'slope/factor/K'
    static fireWindB = 'wind/factor/B'
    static fireWindC = 'wind/factor/C'
    static fireWindE = 'wind/factor/E'
    static fireWindK = 'wind/factor/K'
    static fireWindI = 'wind/factor/I'

    // SurfaceFireWtgModule
    static wtgMod    = 'SurfaceFireWtgModule'
    static wtgSelf   = 'fire/'
    static wtgCover1 = 'cover/primary'
    static wtgCover2 = 'cover/secondary'
    static wtgRosArith = 'spread rate/arithmetic mean'
    static wtgRosHarm = 'spread rate/harmonic mean'

    // SurfaceFuelModel
    static fueldMod  = 'SurfaceFuelBedModule'
    static fuelSelf = 'bed/'
    static fuelDead = 'dead/'
    static fuelLive = 'live/'
    static fuelEl1  = '1/'
    static fuelEl2  = '2/'
    static fuelEl3  = '3/'
    static fuelEl4  = '4/'
    static fuelEl5  = '5/'
    static fuelBulk = 'bulk density'
    static fuelBeta = 'packing ratio'
    static fuelBopt = 'packing ratio/optimum'
    static fuelBrat = 'packing ratio/ratio'
    static fuelDens = 'fiber density'
    static fuelDepth= 'depth'
    static fuelDiam = 'cylindrical diameter'
    static fuelDrxi = 'dry reaction intensity'
    static fuelEfol = 'effective fuel/ovendry load'
    static fuelEfmc = 'effective fuel/moisture content'
    static fuelEfwl = 'effective fuel/water load'
    static fuelEhn  = 'effective heating number'
    static fuelEtam = 'moisture damping coefficient'
    static fuelEtas = 'mineral damping coefficient'
    static fuelHeat = 'heat of combustion'
    static fuelLeng = 'cylindrical length'
    static fuelLife = 'life category'
    static fuelLoad = 'ovendry fuel load'
    static fuelNet  = 'net ovendry load'
    static fuelMext = 'extinction moisture content'
    static fuelMextf= 'extinction moisture content/factor'
    static fuelMois = 'moisture content'
    static fuelQig  = 'heat of pre-ignition'
    static fuelRxi  = 'reaction intensity'      // MUST BE SAME AS fireRxi
    static fuelRxve = 'reaction intensity/exponent'
    static fuelRxvm = 'reaction intensity/maximum'
    static fuelRxvo = 'reaction intensity/optimum'
    static fuelSa   = 'surface area'
    static fuelSavr = 'surface area-to-volume ratio'
    static fuelSavr15 = 'surface area-to-volume ratio/**1.5'
    static fuelSawf = 'surface area weighting factor'
    static fuelScar = 'size class weighting array'
    static fuelScwf = 'size class weighting factor'
    static fuelSeff = 'silica-free mineral content'
    static fuelSink = 'heat sink'
    static fuelSize = 'size class'
    // static fuelSlpk  = 'slope/factor K'
    static fuelSource = 'heat source'
    static fuelStot = 'total mineral content'
    static fuelType = 'fuel type'
    static fuelVol  = 'volume'
    static fuelWsrf = 'wind/speed/reduction/factor/'
    static fuelXi   = 'propagating flux ratio'

    // WindDirectionModule
    static wdirMod          = 'WindDirectionModule'
    static wdirSelf         = 'wind/direction/'
    static wdirHeadFromUp   = 'heading/from up-slope'
    static wdirSourceFromUp = 'source/from up-slope'
    static wdirHeadFromNo   = 'heading/from north'
    static wdirSourceFromNo = 'source/from north'

    // WindSpeedModule
    static wspdMod  = 'WindSpeedModule'
    static wspdSelf = 'wind/speed/'
    static wspd20ft = 'at 20-ft'
    static wspd10m  = 'at 10-m'

    // WindSpeedReductionModule
    static wsrfMod      = 'WindSpeedReductionModule'
    static wsrfSelf     = 'wind/speed/reduction/factor/'
    static wsrfMidflame = 'midflame'
}